trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  containerRegistry: dockerHubService

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: runtime

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    projects: '**/*.csproj'
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'dockerHubService'
    dockerComposeFile: '**/docker-compose.yml'
    additionalDockerComposeFiles: docker-compose.override.yml
    action: 'Build services'
    includeLatestTag: true

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'dockerHubService'
    dockerComposeFile: '**/docker-compose.yml'
    additionalDockerComposeFiles: docker-compose.override.yml
    action: 'Push services'
    includeLatestTag: true

- task: ServiceFabricComposeDeploy@0
  inputs:
    clusterConnection: 'serviceFabricDemo'
    composeFilePath: '**/docker-compose.yml'
    applicationName: 'fabric:/AperioDemo'
    registryCredentials: 'ContainerRegistryEndpoint'
    dockerRegistryConnection: 'dockerHubService'