version: '3.4'

services:
  db:
    image: postgres:12.1
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=riverfuzz
      - POSTGRES_PASSWORD=3r!T8*Qb8YNFlG8Eb8u
    volumes:
      - "postgres:/var/lib/postgresql/data"

  # UI runs at localhost:5000
  webview:
    image: ${DOCKER_REGISTRY-}webview
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - weblauncher
      - db
    build:
      context: .
      dockerfile: WebView/Dockerfile

  weblauncher:
    image: ${DOCKER_REGISTRY-}weblauncher
    expose:
      - "80"
      - "443"
    depends_on:
      - db
    build:
      context: .
      dockerfile: WebLauncher/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=aperio
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

volumes:
  postgres: