version: '3.4'

services:
  webview:
    image: ${DOCKER_REGISTRY-}webview
    build:
      context: .
      dockerfile: WebView/Dockerfile
    networks:
      - database
    depends_on:
      - db
  weblauncher:
    image: ${DOCKER_REGISTRY-}weblauncher
    build:
      context: .
      dockerfile: WebLauncher/Dockerfile
    networks:
      - database
    depends_on:
      - db
  db:
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=riverfuzz
      - POSTGRES_PASSWORD=3r!T8*Qb8YNFlG8Eb8u
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      - database

volumes:
  postgres:

networks:
  database:
    driver: bridge