version: '3'
services:
  db:
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=riverfuzz
      - POSTGRES_PASSWORD=3r!T8*Qb8YNFlG8Eb8u
    volumes:
      - "postgres:/var/lib/postgresql/data"

  juice-shop:
    image: bkimminich/juice-shop:v9.3.1
    ports:
      - "80:3000"

volumes:
  postgres: