version: '3.4'

services:
  webview:
    image: rmkerr/webview
    networks:
      - database
    depends_on:
      - db
    ports:
      - "8080:80"
  weblauncher:
    image: rmkerr/weblauncher
    networks:
      - database
    depends_on:
      - db
  db:
    image: postgres:12.1
    environment:
      - POSTGRES_DB=riverfuzz
      - POSTGRES_PASSWORD=3r!T8*Qb8YNFlG8Eb8u
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      - database

volumes:
  postgres:

networks:
  database:
    driver: bridge