version: '3.4'

services:
  webview:
    build:
      context: .
      dockerfile: WebView/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  weblauncher:
    build:
      context: .
      dockerfile: WebLauncher/Dockerfile
  db:
    ports:
      - "5432:5432"